# Generated by Django 2.2.4 on 2019-08-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('rated', models.CharField(max_length=10, null=True)),
                ('released', models.DateField(null=True)),
                ('runtime', models.CharField(max_length=15, null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('director', models.CharField(max_length=50, null=True)),
                ('writer', models.CharField(max_length=500, null=True)),
                ('actors', models.CharField(max_length=500, null=True)),
                ('plot', models.CharField(max_length=1000, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('awards', models.CharField(max_length=200, null=True)),
                ('poster', models.CharField(max_length=1000, null=True)),
                ('metascore', models.IntegerField(null=True)),
                ('imdbRating', models.FloatField(null=True)),
                ('imdbVotes', models.CharField(max_length=20, null=True)),
                ('imdbID', models.CharField(max_length=100, null=True)),
                ('Type', models.CharField(max_length=10, null=True)),
                ('DVD', models.DateField(null=True)),
                ('boxOffice', models.CharField(max_length=20, null=True)),
                ('production', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApis.Movie')),
            ],
        ),
    ]
